# Generated by Django 5.2.17 on 2026-08-13 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='name_product',
            new_name='name',
        ),
    ]
